[package]
name = "serde-annotated"
version = "0.1.0"
authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]

[dependencies]
serde = "1.0.79"
serde_json = { version = "1.0.32", features = ["raw_value"] }
serde_derive = "1.0.79"

[dev-dependencies]
difference = "2.0.0"
